import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Page1 from "./components/page1"
import Page2 from "./components/page2"
import Page3 from "./components/page3"
import Page4 from "./components/page4"

import {AiOutlineMail, AiOutlineLinkedin, AiOutlineInstagram, AiOutlineGithub, AiOutlineWhatsApp} from 'react-icons/ai';
import Link from 'next/link'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Anna Lara</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Page1/>
        <Page2/>
        <Page3/>
        <Page4/>
      </main>

      <footer className={styles.footer}>
        <div className={styles.footerContainer}>
          <div>
            <h3>Anna Lara Moraes Caixeta</h3>
            <div className={styles.contactItem}>
            <Link  href="https://wa.me/4915752946337">
              <a className={styles.contactIcon}><AiOutlineWhatsApp style={{marginRight: 6}}/>+49 1575 2976337</a>
            </Link>
            </div>
            <div className={styles.contactItem}>
            <Link href="mailto:annalara1426@gmail.com">
            <a className={styles.contactIcon}><AiOutlineMail style={{marginRight: 6}}/>annalara1426@gmail.com</a>
            </Link>
            </div>
          </div>
          <div>
            <h3>Mídias sociais</h3>
            <div className={styles.contactItem}>
            <Link  href="https://www.linkedin.com/in/anna-lara-moraes-39827983/">
              <a className={styles.contactIcon}><AiOutlineLinkedin style={{marginRight: 6}}/>Anna Lara Moraes</a>
            </Link>
            </div>
            <div className={styles.contactItem}>
            <Link href="https://www.instagram.com/annalara.dev/">
            <a className={styles.contactIcon}><AiOutlineInstagram style={{marginRight: 6}}/>@annalara.dev</a>
            </Link>
            </div>
            <div className={styles.contactItem}>
            <Link  href="https://github.com/AnnaLaraMoraes">
              <a className={styles.contactIcon}><AiOutlineGithub style={{marginRight: 6}}/>AnnaLaraMoraes</a>
            </Link>
            </div>
          </div>
        </div>
      </footer>
    </div>
  )
}
