import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Page1 from './components/page1';
import Page2 from './components/page2';
import Page3 from './components/page3';
import Page4 from './components/page4';
import { useState } from 'react';

import {
  AiOutlineMail,
  AiOutlineLinkedin,
  AiOutlineInstagram,
  AiOutlineGithub,
  AiOutlineWhatsApp,
} from 'react-icons/ai';
import { HiOutlineLocationMarker } from 'react-icons/hi';
import Link from 'next/link';
import translate from '../static/translations.json';

export default function Home() {
  const [selectedLanguageButton, setSelectedLanguageButton] = useState('en');

  const [selectedLanguage, setSelectedLanguage] = useState(translate.en);

  const handleSetSelectLanguage = (language) => {
    setSelectedLanguage(translate[language]);
  };

  return (
    <div>
      <style>
        @import
        url(&apos;https://fonts.googleapis.com/css2?family=Roboto+Mono:wght@300&display=swap&apos;);
      </style>
      <Head>
        <title>CV Anna Lara</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className={styles.buttonsLanguage}>
          <button
            onClick={() => {
              handleSetSelectLanguage('pt');
              setSelectedLanguageButton('pt');
            }}
            className={`${styles.button} ${
              selectedLanguageButton === 'pt' && styles.selectLanguage
            }`}
          >
            PT
          </button>
          <button
            onClick={() => {
              handleSetSelectLanguage('en');
              setSelectedLanguageButton('en');
            }}
            className={`${styles.button} ${
              selectedLanguageButton === 'en' && styles.selectLanguage
            }`}
          >
            EN
          </button>
          <button
            onClick={() => {
              handleSetSelectLanguage('de');
              setSelectedLanguageButton('de');
            }}
            className={`${styles.button} ${
              selectedLanguageButton === 'de' && styles.selectLanguage
            }`}
          >
            DE
          </button>
        </div>
        <Page1 selectedLanguage={selectedLanguage} />
        <Page2 selectedLanguage={selectedLanguage} />
        <Page3 selectedLanguage={selectedLanguage} />
        <Page4 selectedLanguage={selectedLanguage} />
      </main>

      <footer className={styles.footer}>
        <div className={styles.footerContainer}>
          <div>
            <h3>Anna Lara Moraes Caixeta</h3>
            <div className={styles.contactItem}>
              <Link href="https://wa.me/4915752946337">
                <a className={styles.contactIcon}>
                  <AiOutlineWhatsApp style={{ marginRight: 6 }} />
                  +49 1575 2976337
                </a>
              </Link>
            </div>
            <div className={styles.contactItem}>
              <Link href="mailto:annalara1426@gmail.com">
                <a className={styles.contactIcon}>
                  <AiOutlineMail style={{ marginRight: 6 }} />
                  annalara1426@gmail.com
                </a>
              </Link>
            </div>
            <div>
              <HiOutlineLocationMarker style={{ marginRight: 6 }} />
              {selectedLanguage.footerAddress}
            </div>
          </div>
          <div>
            <h3>{selectedLanguage.footertitle2}</h3>
            <div className={styles.contactItem}>
              <Link href="https://www.linkedin.com/in/anna-lara-moraes-39827983/">
                <a className={styles.contactIcon}>
                  <AiOutlineLinkedin style={{ marginRight: 6 }} />
                  Anna Lara Moraes
                </a>
              </Link>
            </div>
            <div className={styles.contactItem}>
              <Link href="https://www.instagram.com/annalara.dev/">
                <a className={styles.contactIcon}>
                  <AiOutlineInstagram style={{ marginRight: 6 }} />
                  @annalara.dev
                </a>
              </Link>
            </div>
            <div className={styles.contactItem}>
              <Link href="https://github.com/AnnaLaraMoraes">
                <a className={styles.contactIcon}>
                  <AiOutlineGithub style={{ marginRight: 6 }} />
                  AnnaLaraMoraes
                </a>
              </Link>
            </div>
          </div>
        </div>
      </footer>
    </div>
  );
}
